// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/create": {
            "put": {
                "description": "new full deck, or one based on a given set of cards, maybe shuffled.",
                "consumes": [
                    "*/*"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "deck"
                ],
                "summary": "Creates a new deck.",
                "parameters": [
                    {
                        "type": "boolean",
                        "description": "if new deck needs to be shuffled",
                        "name": "shuffled",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "komma separated list of card codes to init deck with",
                        "name": "cards",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/draw": {
            "post": {
                "description": "Pops one or multiple cards from the top of a given deck.",
                "consumes": [
                    "*/*"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cards"
                ],
                "summary": "Draws some cards from a deck.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "identifier of the deck about to draw cards from",
                        "name": "deck_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "number of cards to draw from the deck",
                        "name": "count",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/open": {
            "get": {
                "description": "returns current content of a deck.",
                "consumes": [
                    "*/*"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "deck"
                ],
                "summary": "Opens a deck.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "identifier of the deck about to open",
                        "name": "deck_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/v1",
	Schemes:          []string{},
	Title:            "Card Fun Demo",
	Description:      "This is a card deck simulator server demo.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
