package testhelp

var SomeCodes = []string{"AS", "2S", "3S", "4C", "5H", "6D", "7D", "8S", "9H", "TD"}

var SomeCards = []map[string]string{
	{"code": "AS", "suit": "SPADES", "value": "ACE"},
	{"code": "2S", "suit": "SPADES", "value": "2"},
	{"code": "3S", "suit": "SPADES", "value": "3"},
	{"code": "4C", "suit": "CLUBS", "value": "4"},
	{"code": "5H", "suit": "HEARTS", "value": "5"},
	{"code": "6D", "suit": "DIAMONDS", "value": "6"},
	{"code": "7D", "suit": "DIAMONDS", "value": "7"},
	{"code": "8S", "suit": "SPADES", "value": "8"},
	{"code": "9H", "suit": "HEARTS", "value": "9"},
	{"code": "TD", "suit": "DIAMONDS", "value": "10"},
}

var AllCodes = []string{
	"AS", "2S", "3S", "4S", "5S", "6S", "7S", "8S", "9S", "TS", "JS", "QS", "KS",
	"AD", "2D", "3D", "4D", "5D", "6D", "7D", "8D", "9D", "TD", "JD", "QD", "KD",
	"AC", "2C", "3C", "4C", "5C", "6C", "7C", "8C", "9C", "TC", "JC", "QC", "KC",
	"AH", "2H", "3H", "4H", "5H", "6H", "7H", "8H", "9H", "TH", "JH", "QH", "KH",
}

var AllCards = []map[string]string{
	{"code": "AS", "suit": "SPADES", "value": "ACE"},
	{"code": "2S", "suit": "SPADES", "value": "2"},
	{"code": "3S", "suit": "SPADES", "value": "3"},
	{"code": "4S", "suit": "SPADES", "value": "4"},
	{"code": "5S", "suit": "SPADES", "value": "5"},
	{"code": "6S", "suit": "SPADES", "value": "6"},
	{"code": "7S", "suit": "SPADES", "value": "7"},
	{"code": "8S", "suit": "SPADES", "value": "8"},
	{"code": "9S", "suit": "SPADES", "value": "9"},
	{"code": "TS", "suit": "SPADES", "value": "10"},
	{"code": "JS", "suit": "SPADES", "value": "JACK"},
	{"code": "QS", "suit": "SPADES", "value": "QUEEN"},
	{"code": "KS", "suit": "SPADES", "value": "KING"},
	{"code": "AD", "suit": "DIAMONDS", "value": "ACE"},
	{"code": "2D", "suit": "DIAMONDS", "value": "2"},
	{"code": "3D", "suit": "DIAMONDS", "value": "3"},
	{"code": "4D", "suit": "DIAMONDS", "value": "4"},
	{"code": "5D", "suit": "DIAMONDS", "value": "5"},
	{"code": "6D", "suit": "DIAMONDS", "value": "6"},
	{"code": "7D", "suit": "DIAMONDS", "value": "7"},
	{"code": "8D", "suit": "DIAMONDS", "value": "8"},
	{"code": "9D", "suit": "DIAMONDS", "value": "9"},
	{"code": "TD", "suit": "DIAMONDS", "value": "10"},
	{"code": "JD", "suit": "DIAMONDS", "value": "JACK"},
	{"code": "QD", "suit": "DIAMONDS", "value": "QUEEN"},
	{"code": "KD", "suit": "DIAMONDS", "value": "KING"},
	{"code": "AC", "suit": "CLUBS", "value": "ACE"},
	{"code": "2C", "suit": "CLUBS", "value": "2"},
	{"code": "3C", "suit": "CLUBS", "value": "3"},
	{"code": "4C", "suit": "CLUBS", "value": "4"},
	{"code": "5C", "suit": "CLUBS", "value": "5"},
	{"code": "6C", "suit": "CLUBS", "value": "6"},
	{"code": "7C", "suit": "CLUBS", "value": "7"},
	{"code": "8C", "suit": "CLUBS", "value": "8"},
	{"code": "9C", "suit": "CLUBS", "value": "9"},
	{"code": "TC", "suit": "CLUBS", "value": "10"},
	{"code": "JC", "suit": "CLUBS", "value": "JACK"},
	{"code": "QC", "suit": "CLUBS", "value": "QUEEN"},
	{"code": "KC", "suit": "CLUBS", "value": "KING"},
	{"code": "AH", "suit": "HEARTS", "value": "ACE"},
	{"code": "2H", "suit": "HEARTS", "value": "2"},
	{"code": "3H", "suit": "HEARTS", "value": "3"},
	{"code": "4H", "suit": "HEARTS", "value": "4"},
	{"code": "5H", "suit": "HEARTS", "value": "5"},
	{"code": "6H", "suit": "HEARTS", "value": "6"},
	{"code": "7H", "suit": "HEARTS", "value": "7"},
	{"code": "8H", "suit": "HEARTS", "value": "8"},
	{"code": "9H", "suit": "HEARTS", "value": "9"},
	{"code": "TH", "suit": "HEARTS", "value": "10"},
	{"code": "JH", "suit": "HEARTS", "value": "JACK"},
	{"code": "QH", "suit": "HEARTS", "value": "QUEEN"},
	{"code": "KH", "suit": "HEARTS", "value": "KING"},
}
